name: PyTest

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: >
            uv sync --no-dev --group test 
            --no-install-package mamba-ssm 
            --no-install-package causal-conv1d
            --no-install-package nvidia-cudnn-cu12
            --no-install-package nvidia-cublas-cu12
            --no-install-package nvidia-cusparse-cu12
            --no-install-package nvidia-cusolver-cu12
            --no-install-package nvidia-cufft-cu12
            --no-install-package nvidia-nccl-cu12

      - name: Run Pytest
        run: uv run --no-sync pytest -m "not integration"
